# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDetail',
            fields=[
                ('change_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=150)),
                ('revenue', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('expenses_amount', models.FloatField(default=0, max_length=30)),
                ('members_count', models.IntegerField(default=0)),
                ('expenses_per_person', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eWallet_app.ChangeDetail')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eWallet_app.Group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('account_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eWallet_app.ChangeDetail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eWallet_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eWallet_app.Group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eWallet_app.User')),
            ],
        ),
    ]
