    # -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('account_balance', models.FloatField(default=0)),
            ],
        ),
    ]
